on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - windows-2019
        - windows-2016
        - ubuntu-20.04
        - ubuntu-18.04
        - macos-11.0
        - macos-10.15
    steps:
    - uses: actions/checkout@v2
    - uses: ilammy/msvc-dev-cmd@v1
    - run: bash ./build.sh
      env:
        NEOMURA_SETUP_ASEPRITE_CLI_ACTION_REPOSITORY: ${{ GITHUB.REPOSITORY }}
        NEOMURA_SETUP_ASEPRITE_CLI_ACTION_REF: ${{ GITHUB.REF }}
    - run: bash ./install-test-dependencies.sh
    - run: bash ./test.sh
