on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - windows-2019
        - windows-2016
        - ubuntu-20.04
        - ubuntu-18.04
        - ubuntu-16.04
        - macos-11.0
        - macos-10.15
    steps:
    - uses: ilammy/msvc-dev-cmd@v1
    - run: bash build.sh
